server:
  port: 9001


spring:
  application:
    name: DEPARTEMENT-SERVICE
  cloud:
    consul:
      host: consul
      port: 8500

  zipkin:
    base-url: http://zipkin:9411 # Zipkin server URL
  sleuth:
    sampler:
      probability: 1.0
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
